### ISSUE TITLE
Monaca cordova6.2 Androidでncmbを呼ぶとアプリが100%クラッシュする

### ISSUE THREAD

**Issue by kenkisaragi** [NIFTYCloud-mbaas/monaca_push_plugin#10]
## 不具合の概要(Description of bug)

タイトルの通り、MonacaのCordova6.2プロジェクト（Android）で
Niftyモバイルバックエンドver.2のCordovaプラグインを利用してビルドしたアプリ
（デバッグビルド、リリースビルドどちらも）で、ncmbを呼ぶとアプリが必ずクラッシュして終了します。
- SDKのバージョン(SDK version)
  ncmb-push-monaca-plugin v2.0.2
- 不具合が発生した環境(Environment requirement)
  Monaca cordova6.2プロジェクト　Android
  実機はNexus5x (android6.0.1）
- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
  御社で公開しているMonaca用のアプリ側導入用のサンプルコードで確認頂けます。
- エラーメッセージ(Error messages)
  「問題が発生したため～」という実機にて表示されるメッセージ表示と同時にアプリ終了となります。

**Comment by oonoyosp** [comment]
#12  で対応
